### ISSUE TITLE
Excessive resources are requested in reduce phase after hive queries the paimon table. Procedure

### ISSUE THREAD

**Issue by Dkbei** [JingsongLi/paimon-trino#11]
Compare the paimon table and hive table with the same statement and data amount using the hive client:
painmon table:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/38800374/230321465-c0f52b5d-5646-4275-ab3c-ef7c7c3ab7bb.png">

hive table：
<img width="608" alt="image" src="https://user-images.githubusercontent.com/38800374/230321903-4d63d18d-24af-4ce6-888c-d7eacf40d81d.png">

Is there any room for optimization？

**Comment by JingsongLi** [comment]
Migrated to https://github.com/apache/incubator-paimon/issues/864
